DELETE http://localhost:3004/api/blogs/61b884473f8b9a51e025cd92
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MWI4ODNmYmUwOWE1NjMwMTgwYTY0OGYiLCJpYXQiOjE2Mzk0ODMwNjMsImV4cCI6MTYzOTQ4NjY2M30.1fHnPsEUkAdiCPtdvseYjjtBP8OnEjBKM83O055OCTk